//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dip.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vhodHis
    {
        public int id { get; set; }
        public Nullable<int> id_users { get; set; }
        public Nullable<System.DateTime> DateTimeLog { get; set; }
        public string TypeVhod { get; set; }
    
        public virtual users users { get; set; }
    }
}
